### ISSUE TITLE
Just dropping in to say hi, and this is awesome!

### ISSUE THREAD

**Issue by Ben-PH** [cmore839/DIY-Linear-Motor#1]
Love this project. It's something that I've been wanting to do for a while. I got a magnet assembly sorted, and have a rotary encoder on order. I see that you've gone about position encoding in a much nicer way, I think.

I would like to build something like this myself, though with some slight differences. would you be happy to get in touch over discord or something?

**Comment by cmore839** [comment]
Hey, thanks for saying hello, sounds awesome, would be great to see more. Discord is already started, you can find us at https://discord.gg/MjB4ArvR
