### ISSUE TITLE
Discord Invite has expired. 

### ISSUE THREAD

**Issue by bhb1** [cmore839/DIY-Linear-Motor#2]
Great work and very cool project! Attempting to replicate and wanted to talk with others interested. Is it possible to get a current discord link?

**Comment by cmore839** [comment]
Hey, thats weird I thought I used a forever link on the discord invite. Can you try again?
https://discord.gg/5FmVrjaZHb

**Comment by bhb1** [comment]
That one works! Probably something on my end. Thank you.
